# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Downlaoding the UA"
    curl -LJ "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar" -o "UA.jar"
    echo "Downlaoding the CLI"
    curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
  displayName: 'Download Scanners'

- script: |
    echo "Verifying the UA"
    java -jar "UA.jar" -v
    echo "Verifying the CLI"
    mend version
  displayName: 'Verifying the Scanners'

- script: java -jar UA.jar
  env:
    WS_PYTHON_RUNPOETRYPRESTEP: true
    WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
    WS_PRODUCTNAME: $(Build.Repository.Name)
    WS_USERKEY: $(WS_USERKEY)
    WS_APIKEY: $(WS_APIKEY)
    WS_LOG_LEVEL: "DEBUG"
    WS_SHOWPROGRESSBAR: false
  displayName: 'Run UA'

- script: pip install .
  displayName: 'Build Dep for CLI'

- script: mend dep --update --scope "$(Build.Repository.Name)//$(Build.SourceBranchName)" --non-interactive -e
  env:
    MEND_USER_KEY: $(WS_USERKEY)
    MEND_EMAIL: $(MEND_EMAIL)
    MEND_URL: $(MEND_URL)
    MEND_LOG_LEVEL: "DEBUG"
  displayName: 'Run CLI'

